# Generated by Django 4.0.4 on 2022-06-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_motorista_alter_veiculo_marca_alter_veiculo_placa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField()),
                ('hora_saida', models.TimeField()),
                ('km_saida', models.IntegerField()),
                ('destino', models.CharField(max_length=255)),
                ('data_retorno', models.DateTimeField()),
                ('hora_retorno', models.TimeField()),
                ('km_retorno', models.IntegerField()),
                ('km_percorrido', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locadora.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locadora.veiculo')),
            ],
        ),
    ]
