# Generated by Django 4.0.4 on 2022-06-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_controle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='controle',
            name='update_at',
        ),
    ]
